#! /bin/bash
sleep 10
if [ ! -f ~/.wine/drive_c/Program\ Files\ \(x86\)/SoulseekQt/SoulseekQt.exe ] ; then
  export TERM=xterm
  export DISPLAY=":1"
  wine /bin/SoulseekQt-2015-6-12.exe
  wine ~/.wine/drive_c/Program\ Files\ \(x86\)/SoulseekQt/SoulseekQt.exe
fi
